name: Basic Lint and Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.7
          auto-update-conda: true
          channels: conda-forge
          activate-environment: ksmm
          environment-file: environment.yaml

      - shell: bash -l {0}
        run: |
          pip install -e .

      - shell: bash -l {0}
        run: |
          pip install -e .

